# Generated by Django 5.2.4 on 2025-07-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FSTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("flag", models.CharField(blank=True, max_length=5, null=True)),
                ("photo", models.ImageField(upload_to="fsteam-photos/")),
            ],
        ),
        migrations.CreateModel(
            name="FSTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("is_driver", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.fsteam"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FSTimeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_result", models.DurationField()),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ACC", "Acceleration"),
                            ("SKD", "Skidpad"),
                            ("AUX", "Autocross"),
                            ("END", "Endurance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.fsteammember",
                    ),
                ),
            ],
        ),
    ]
