# Generated by Django 5.2.4 on 2025-07-28 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fsteam",
            old_name="photo",
            new_name="logo",
        ),
    ]
