# Generated by Django 5.2.4 on 2025-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_photo_fsteam_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fstimeresult",
            name="event",
            field=models.CharField(
                choices=[
                    ("ACCELERATION", "Acceleration"),
                    ("SKIDPAD", "Skidpad"),
                    ("AUTOX", "Autocross"),
                    ("ENDURANCE", "Endurance"),
                ],
                max_length=50,
            ),
        ),
    ]
