# Generated by Django 5.2.4 on 2025-07-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_fstimeresult_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fstimeresult",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.fsteammember",
            ),
        ),
    ]
