# Generated by Django 5.2.4 on 2025-07-29 09:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_fstimeresult_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="fstimeresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 29, 9, 11, 41, 495407, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
