# Generated by Django 5.2.4 on 2025-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fsteammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsteam',
            name='fsbk_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fsteammember',
            name='fsbk_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
